name: continuous-integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:

  developer-environment:
    strategy:
      matrix:
        include:
          - os: macos-latest
            label: macOS
          - os: windows-latest
            label: win-64
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.3
          cache: true
      - name: Run Tests
        shell: pwsh
        run: pixi run test-core
