name: continuous-integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:

  developer-environment:
    strategy:
      fail-fast: true
      matrix:
        command: [test-core, test-estimation, test-estimation-nb]
        include:
          - os: macos-latest
            label: macOS
          - os: windows-latest
            label: Windows
          - command: test-core
            tag: Run Tests
          - command: test-estimation
            tag: Run Estimation Tests
          - command: test-estimation-nb
            tag: Test Estimation Notebooks
    name: ${{ matrix.label }}-${{ matrix.command }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.3
          cache: true
      - name: ${{ matrix.tag }}
        run: pixi run ${{ matrix.command }}
