name: continuous-integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:

  developer-windows:
    name: windows-64-py3.10
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Pixi
        shell: pwsh
        run: iwr -useb https://pixi.sh/install.ps1 | iex
      - name: Run Tests
        shell: pwsh
        run: pixi run test-core

  developer-macos:
    name: macos-64-py3.10
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash
      - name: Run Tests
        run: pixi run test-core
